### ISSUE TITLE
Item name

### ISSUE THREAD

**Issue by TugaPowerROM** [Musiker15/chezza_plugins#2]
The inventory is saving the item name over the lockers in database, if change the item name over the database the inventory hangs opening the lockers, any idea to fix this ?

**Comment by Musiker15** [comment]
Probably because the item does not exist

**Comment by TugaPowerROM** [comment]
No, the item exists but the label its diffeent, for example, we save something, over the database it will be saved the name and the label of the item, but if go and change the label of the item over the database of items, the storage pluggin will go crazy when trying to acess, it will not open because it have items saveed with different label.

**Comment by Musiker15** [comment]
Then dont change the label
